from __future__ import annotations

import re
from dataclasses import dataclass


@dataclass(frozen=True)
class ParsedSurfaceMap:
    size: int
    # terrain_by_xy[(x,y)] -> terrain name (e.g. "Plains")
    terrain_by_xy: dict[tuple[int, int], str]


# Canonical symbol mapping from Stellar Dominion engine/maps/surface_gen.py
_TERRAIN_TO_SYMBOL: dict[str, str] = {
    "Shallows": "~",
    "Sea": "S",
    "Ice": "#",
    "Tundra": ":",
    "Grassland": '"',
    "Plains": ".",
    "Forest": "T",
    "Jungle": "&",
    "Swamp": "%",
    "Marsh": ";",
    "Hills": "^",
    "Mountains": "A",
    "Rock": "_",
    "Dust": ",",
    "Crater": "o",
    "Volcanic": "!",
    "Desert": "=",
    "Cultivated": "+",
    "Ruin": "?",
    "Urban": "@",
    "Gas": "*",
}
_SYMBOL_TO_TERRAIN: dict[str, str] = {v: k for k, v in _TERRAIN_TO_SYMBOL.items()}

_TITLE_RE = re.compile(r"^\s*Surface Map:\s+.+\(\d+\)\s+\[(?P<w>\d+)x(?P<h>\d+)\]\s*$", re.IGNORECASE)
_ROW_RE = re.compile(r"^\s*(?P<y>\d+)\s+(?P<body>.+?)\s+(?P=y)\s*$")


def parse_scansurface_ascii(text: str) -> ParsedSurfaceMap | None:
    """
    Parse Phoenix-style SCANSURFACE output (as generated by Stellar Dominion) into a terrain grid.

    We intentionally ignore non-terrain info blocks (planetary data, ports, etc.).
    Returns None if no surface map grid is detected.
    """
    lines = text.splitlines()

    size: int | None = None
    title_idx: int | None = None
    for i, line in enumerate(lines):
        m = _TITLE_RE.match(line)
        if m:
            try:
                w = int(m.group("w"))
                h = int(m.group("h"))
            except ValueError:
                return None
            if w <= 0 or h <= 0 or w != h:
                return None
            size = w
            title_idx = i
            break

    if size is None or title_idx is None:
        return None

    terrain_by_xy: dict[tuple[int, int], str] = {}

    # After the title there is typically a blank line, then a column header line,
    # then `size` row lines like:
    # " 31   _  _  . ...  31"
    # The row body is a sequence of tokens (we only care about 1-char symbols and "X").
    for line in lines[title_idx + 1 :]:
        rm = _ROW_RE.match(line)
        if not rm:
            continue
        try:
            y = int(rm.group("y"))
        except ValueError:
            continue
        if y < 1 or y > size:
            continue

        body = rm.group("body")
        tokens = [t for t in body.split() if t]
        # Expect exactly `size` symbols; allow extra noise by taking only 1-char tokens.
        symbols = [t for t in tokens if len(t) == 1]
        if len(symbols) < size:
            # Some renderers might omit spacing; bail on this row.
            continue
        symbols = symbols[:size]

        for x, sym in enumerate(symbols, start=1):
            if sym == "X":
                terrain_by_xy[(x, y)] = "Ship"
                continue
            terrain = _SYMBOL_TO_TERRAIN.get(sym)
            if terrain:
                terrain_by_xy[(x, y)] = terrain

    if not terrain_by_xy:
        return None

    return ParsedSurfaceMap(size=size, terrain_by_xy=terrain_by_xy)

